cijferICOR= (7 * 30)
cijferPROG= (7.5 * 30)
cijferCSN= (6 * 30)
gemiddelde=((cijferCSN+cijferICOR+cijferPROG)/3)
totaal=(cijferCSN+cijferICOR+cijferPROG)
print ('mijn' + ' ' + 'cijfers' + ' ' + (str(gemiddelde / 30)) + ' ' + 'leveren' + ' ' + 'een' + ' ' + 'beloning' + ' ' + 'van' + ' ' + '€' + (str(totaal)) + ' ' + 'op')
